spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  main:
    allow-bean-definition-overriding: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable: true


  h2:
    console:
      enabled: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  datasource:
    url: jdbc:mariadb://${DB_URL}/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}


cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-Key: ${AWS_ACCESS}
      secret-Key: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      url: ${AWS_URL}